### ISSUE TITLE
Plugin dead but getting updates

### ISSUE THREAD

**Issue by nd2s** [python-otr/gajim-otr#22]
This repository says the plugin is dead, I also don't see any new commits. Nonetheless I am getting updates in the Gajim plugins manager (new version: 1.9.2).

Can someone explain?

**Comment by afflux** [comment]
Quoting from the FAQ:

> ## What's the relationship between the plugin in Gajim's plugin manager and this repository?
> [This repository](https://github.com/python-otr/gajim-otr) is the official source. The [gajim-plugins](http://hg.gajim.org/gajim-plugins/) repository feeds into the Gajim plugin manager. The author of this plugin has push access to the Gajim repository, and so does any other plugin author. In some cases, Gajim authors cherry-pick unmerged pull requests or bug fixes into their repository and push the version of the plugin so the plugin manager will deploy the new commits. This is when the repositories and the version number diverges.
