### ISSUE TITLE
Has this project moved from trac?

### ISSUE THREAD

**Issue by ntrrgc** [python-otr/gajim-otr#7]
I reported this 4 months ago, patch included: https://trac-plugins.gajim.org/ticket/89

Since then, I haven't received any reply. Today I got told you manage the project here now... So what about the old tracker? Is it being checked by maintainers, is no longer used by this project or has just been inactive this long?

**Comment by afflux** [comment]
The gajim trac was never the official tracker for this project. It was created by the Gajim devs and was given to us and I checked it whenever I got the chance. (However, the whole gajim-otr project is more or less unmaintained right now)
